name: 'ci/cd'
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  test:
    # Job name
    name: test
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        id: checkout
      - name: Installing pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Installing packages...🏃‍♂️ 🏃‍♂️ 🏃‍♂️
        run: pnpm install
      - name: Running typecheck... 🩺 🔬 🔭
        run: pnpm code:typecheck
      - name: Running eslint... 👀
        run: pnpm code:lint
      - name: Running unit test... 🤞 🚑 💊
        run: pnpm test:unit --runInBand --coverage
      - name: Trigger codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Run build Chrome
        run: pnpm app:chrome
      - name: Run build Firefox
        run: pnpm app:firefox
      - name: Run build Edge
        run: pnpm app:edge
