name: 'ci/cd'
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  installation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-deps
      - name: Installing packages...🏃‍♂️ 🏃‍♂️ 🏃‍♂️
        run: yarn install --frozen-lockfile
  linter:
    runs-on: ubuntu-20.04
    needs: [installation]
    concurrency: validation-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-deps
      - name: Installing packages...🏃‍♂️ 🏃‍♂️ 🏃‍♂️
        run: yarn install --frozen-lockfile
      - name: Running typecheck... 🩺 🔬 🔭
        run: yarn code:typecheck
      - name: Running eslint... 👀
        run: yarn code:lint
  build:
    runs-on: ubuntu-20.04
    needs: [installation, linter]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-deps
      - name: Installing packages...🏃‍♂️ 🏃‍♂️ 🏃‍♂️
        run: yarn install --frozen-lockfile
      - name: Run build Chrome
        run: yarn app:chrome
      - name: Run build Firefox
        run: yarn app:firefox
      - name: Run build Edge
        run: yarn app:edge
